use crate::app::Draft;
use crate::git::DiffSource;
use anyhow::{Context, Result};
use chrono::Utc;
use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};

pub fn drafts_path(root: &Path) -> PathBuf {
    root.join(".gitdiff").join("drafts.json")
}

pub fn review_path(root: &Path) -> PathBuf {
    root.join("REVIEW.md")
}

pub fn load_drafts(root: &Path) -> Result<Vec<Draft>> {
    let p = drafts_path(root);
    if !p.exists() {
        return Ok(Vec::new());
    }
    let raw = fs::read_to_string(&p).with_context(|| format!("read {}", p.display()))?;
    if raw.trim().is_empty() {
        return Ok(Vec::new());
    }
    Ok(serde_json::from_str(&raw).with_context(|| format!("parse {}", p.display()))?)
}

pub fn save_drafts(root: &Path, drafts: &[Draft]) -> Result<()> {
    let p = drafts_path(root);
    if let Some(dir) = p.parent() {
        fs::create_dir_all(dir)?;
    }
    let raw = serde_json::to_string_pretty(drafts)?;
    fs::write(&p, raw).with_context(|| format!("write {}", p.display()))?;
    Ok(())
}

pub fn write_review(
    root: &Path,
    source: &DiffSource,
    source_label: &str,
    base_sha: Option<&str>,
    head_sha: Option<&str>,
    drafts: &[Draft],
) -> Result<PathBuf> {
    let p = review_path(root);
    let mut out = String::new();
    out.push_str("# Code Review\n\n");
    out.push_str(&format!(
        "Generated by gitdiff on {}\n",
        Utc::now().format("%Y-%m-%dT%H:%M:%SZ")
    ));
    out.push_str(&format!("Source: {source_label}\n"));
    if let (Some(b), Some(h)) = (base_sha, head_sha) {
        out.push_str(&format!("Range: {b} .. {h}\n"));
    }
    let _ = source; // reserved for future use (per-source phrasing)
    out.push_str(&format!(
        "Status: {} open · 0 resolved\n\n---\n\n",
        drafts.len()
    ));

    if drafts.is_empty() {
        out.push_str("_No comments yet._\n");
        fs::write(&p, out)?;
        return Ok(p);
    }

    // group by file, preserve insertion order via BTreeMap of Vec
    let mut by_file: BTreeMap<String, Vec<&Draft>> = BTreeMap::new();
    for d in drafts {
        by_file.entry(d.file_path.clone()).or_default().push(d);
    }

    for (file, mut entries) in by_file {
        entries.sort_by_key(|d| d.new_lineno.unwrap_or(d.old_lineno.unwrap_or(0)));
        out.push_str(&format!("## {file}\n\n"));
        for d in entries {
            let anchor = d.anchor_label();
            out.push_str(&format!("### {anchor} · open\n\n"));
            out.push_str("Original:\n\n");
            out.push_str("```diff\n");
            out.push_str(&d.diff_snippet);
            if !d.diff_snippet.ends_with('\n') {
                out.push('\n');
            }
            out.push_str("```\n\n");
            out.push_str(&format!(
                "**Comment** ({}):\n\n",
                d.created_at.format("%Y-%m-%d %H:%M UTC")
            ));
            for line in d.body.lines() {
                out.push_str("> ");
                out.push_str(line);
                out.push('\n');
            }
            out.push_str("\n---\n\n");
        }
    }

    fs::write(&p, out).with_context(|| format!("write {}", p.display()))?;
    Ok(p)
}
