use crate::app::{Draft, Reply, Verdict};
use crate::git::DiffSource;
use anyhow::{Context, Result};
use chrono::{DateTime, Utc};
use std::collections::{BTreeMap, HashMap};
use std::fs;
use std::path::{Path, PathBuf};

pub fn drafts_path(root: &Path, source: &DiffSource) -> PathBuf {
    root.join(".gitdiff")
        .join(format!("drafts-{}.json", source.slug()))
}

pub fn viewed_path(root: &Path, source: &DiffSource) -> PathBuf {
    root.join(".gitdiff")
        .join(format!("viewed-{}.json", source.slug()))
}

pub fn review_path(root: &Path, source: &DiffSource) -> PathBuf {
    root.join(format!("REVIEW-{}.md", source.slug()))
}

/// Viewed entries store a hash of the file's diff content at the time the
/// user marked it viewed. On load we drop entries whose hash no longer matches
/// the current diff, so re-edits clear the tick automatically.
pub fn load_viewed(root: &Path, source: &DiffSource) -> Result<HashMap<String, String>> {
    let p = viewed_path(root, source);
    if !p.exists() {
        return Ok(HashMap::new());
    }
    let raw = fs::read_to_string(&p).with_context(|| format!("read {}", p.display()))?;
    if raw.trim().is_empty() {
        return Ok(HashMap::new());
    }
    if let Ok(m) = serde_json::from_str::<HashMap<String, String>>(&raw) {
        return Ok(m);
    }
    // Fall back to the pre-hash array format. Entries land with empty hashes,
    // which will fail the hash check at startup and be cleared — that's the
    // intended behaviour for a one-time format upgrade.
    if let Ok(v) = serde_json::from_str::<Vec<String>>(&raw) {
        return Ok(v.into_iter().map(|p| (p, String::new())).collect());
    }
    Ok(HashMap::new())
}

pub fn save_viewed(
    root: &Path,
    source: &DiffSource,
    viewed: &HashMap<String, String>,
) -> Result<()> {
    let p = viewed_path(root, source);
    if let Some(dir) = p.parent() {
        fs::create_dir_all(dir)?;
    }
    // BTreeMap for stable key ordering in the on-disk file.
    let sorted: BTreeMap<&String, &String> = viewed.iter().collect();
    fs::write(&p, serde_json::to_string_pretty(&sorted)?)
        .with_context(|| format!("write {}", p.display()))?;
    Ok(())
}

pub fn load_drafts(root: &Path, source: &DiffSource) -> Result<Vec<Draft>> {
    let p = drafts_path(root, source);
    if !p.exists() {
        return Ok(Vec::new());
    }
    let raw = fs::read_to_string(&p).with_context(|| format!("read {}", p.display()))?;
    if raw.trim().is_empty() {
        return Ok(Vec::new());
    }
    Ok(serde_json::from_str(&raw).with_context(|| format!("parse {}", p.display()))?)
}

pub fn save_drafts(root: &Path, source: &DiffSource, drafts: &[Draft]) -> Result<()> {
    let p = drafts_path(root, source);
    if let Some(dir) = p.parent() {
        fs::create_dir_all(dir)?;
    }
    let raw = serde_json::to_string_pretty(drafts)?;
    fs::write(&p, raw).with_context(|| format!("write {}", p.display()))?;
    Ok(())
}

const AGENT_INSTRUCTIONS: &str = "<!--
INSTRUCTIONS FOR CODING AGENTS (claude-code, codex, gemini, etc.)
=================================================================

You are reading a gitdiff review file. A human wrote the comments under each
`### Lxx ... · thread:tID` heading; your job is to address them.

For each open comment:
  1. Read the comment body and the `Original` diff snippet under the heading.
  2. Make the requested code change in the actual source file, OR write a
     reply explaining why you did not.
  3. Append your reply inside the matching `<!-- replies:tID --> ... <!--
     /replies:tID -->` block, one line per reply line:
         > [@your-handle 2026-05-24T17:05:00Z] your reply text, one line.
     Multi-line reply? Emit several lines with the same author+timestamp.
  4. When the thread is fully addressed (code change shipped or no action
     needed), add a single line `<!-- resolved -->` inside the same replies
     block. gitdiff hides resolved threads from its TUI on the next launch.

Choose any `your-handle` EXCEPT `you` (that handle is reserved for the human
running gitdiff — typical agent handles are claude-code, codex, gemini). Use
ISO-8601 UTC timestamps.

EVERYTHING OUTSIDE THE `<!-- replies:* -->` BLOCKS IS OVERWRITTEN on the
human's next submit. Do not edit there — your changes will be lost. Replies
and the `<!-- resolved -->` marker are preserved across submits.
-->\n\n";

pub fn write_review(
    root: &Path,
    source: &DiffSource,
    source_label: &str,
    base_sha: Option<&str>,
    head_sha: Option<&str>,
    drafts: &[Draft],
    verdict: Verdict,
) -> Result<PathBuf> {
    let p = review_path(root, source);
    let mut out = String::new();
    out.push_str(AGENT_INSTRUCTIONS);
    out.push_str("# Code Review\n\n");
    out.push_str(&format!(
        "Generated by gitdiff on {}\n",
        Utc::now().format("%Y-%m-%dT%H:%M:%SZ")
    ));
    out.push_str(&format!("Source: {source_label}\n"));
    if let (Some(b), Some(h)) = (base_sha, head_sha) {
        out.push_str(&format!("Range: {b} .. {h}\n"));
    }
    out.push_str(&format!("Verdict: {}\n", verdict.label()));
    let _ = source;
    let open = drafts.iter().filter(|d| !d.resolved).count();
    let resolved = drafts.len() - open;
    let outdated = drafts.iter().filter(|d| d.outdated).count();
    out.push_str(&format!(
        "Status: {open} open · {resolved} resolved · {outdated} outdated\n\n---\n\n"
    ));

    if drafts.is_empty() {
        out.push_str("_No comments yet._\n");
        fs::write(&p, out)?;
        return Ok(p);
    }

    write_section(&mut out, "Open", drafts.iter().filter(|d| !d.resolved));
    if resolved > 0 {
        out.push_str("---\n\n# Resolved\n\n");
        write_section(&mut out, "Resolved", drafts.iter().filter(|d| d.resolved));
    }

    fs::write(&p, out).with_context(|| format!("write {}", p.display()))?;
    Ok(p)
}

fn write_section<'a>(out: &mut String, _label: &str, ds: impl Iterator<Item = &'a Draft>) {
    let mut by_file: BTreeMap<String, Vec<&Draft>> = BTreeMap::new();
    for d in ds {
        by_file.entry(d.file_path.clone()).or_default().push(d);
    }
    for (file, mut entries) in by_file {
        entries.sort_by_key(|d| d.new_lineno.unwrap_or(d.old_lineno.unwrap_or(0)));
        out.push_str(&format!("## {file}\n\n"));
        for d in entries {
            let anchor = d.anchor_label();
            let status = if d.resolved {
                "resolved"
            } else if d.outdated {
                "open · outdated"
            } else {
                "open"
            };
            let tid = if d.thread_id.is_empty() {
                "(no-id)"
            } else {
                d.thread_id.as_str()
            };
            out.push_str(&format!("### {anchor} · {status} · thread:{tid}\n\n"));
            out.push_str("Original:\n\n```diff\n");
            out.push_str(&d.diff_snippet);
            if !d.diff_snippet.ends_with('\n') {
                out.push('\n');
            }
            out.push_str("```\n\n");
            out.push_str(&format!(
                "**Comment** (you, {}):\n\n",
                d.created_at.format("%Y-%m-%dT%H:%M:%SZ")
            ));
            for line in d.body.lines() {
                out.push_str("> ");
                out.push_str(line);
                out.push('\n');
            }
            if !d.reactions.is_empty() {
                out.push_str(&format!("\nReactions: {}\n", d.reactions.join(" ")));
            }
            // Replies block — agents must edit only inside this delimiter pair.
            // Timestamps include sub-second precision so the parser round-trips
            // a reply back to the exact same Reply on the next launch (avoids
            // the duplicate-on-merge bug). A blank line separates consecutive
            // replies so the parser doesn't fold them into one multi-line body.
            out.push_str(&format!("\n<!-- replies:{tid} -->\n"));
            for (ri, r) in d.replies.iter().enumerate() {
                if ri > 0 {
                    out.push('\n');
                }
                let ts = r.created_at.format("%Y-%m-%dT%H:%M:%S%.6fZ");
                if r.body.is_empty() {
                    out.push_str(&format!("> [@{} {}]\n", r.author, ts));
                } else {
                    for ln in r.body.lines() {
                        out.push_str(&format!("> [@{} {}] {}\n", r.author, ts, ln));
                    }
                }
            }
            if d.resolved {
                out.push_str("<!-- resolved -->\n");
            }
            out.push_str(&format!("<!-- /replies:{tid} -->\n"));
            out.push_str("\n---\n\n");
        }
    }
}

/// Per-thread payload imported back from a REVIEW-*.md `<!-- replies:tID -->`
/// block.
#[derive(Debug, Default, Clone)]
pub struct ThreadImport {
    pub replies: Vec<Reply>,
    /// True when the agent placed a `<!-- resolved -->` marker inside the block.
    pub resolved: bool,
}

/// Scans a REVIEW-*.md file and extracts all `<!-- replies:tID --> ... <!-- /replies:tID -->`
/// blocks. Returns a thread_id → import map for merging back into the JSON
/// draft store on launch.
pub fn parse_review_replies(text: &str) -> HashMap<String, ThreadImport> {
    let mut out: HashMap<String, ThreadImport> = HashMap::new();
    let mut cursor = 0;
    while let Some(start) = text[cursor..].find("<!-- replies:") {
        let abs_start = cursor + start;
        let head = &text[abs_start..];
        let Some(close_idx) = head.find(" -->") else { break };
        let tid = head["<!-- replies:".len()..close_idx].trim().to_string();
        let body_start = abs_start + close_idx + " -->".len();
        let end_marker = format!("<!-- /replies:{tid} -->");
        let Some(rel_end) = text[body_start..].find(&end_marker) else {
            cursor = body_start;
            continue;
        };
        let body_end = body_start + rel_end;
        let block = &text[body_start..body_end];
        let mut replies = Vec::new();
        let mut resolved = false;
        let mut current: Option<Reply> = None;
        for raw in block.lines() {
            let line = raw.trim_end();
            // Resolve marker. Accept variants for forgiving parsing.
            let trimmed = line.trim();
            if trimmed == "<!-- resolved -->"
                || trimmed == "<!--resolved-->"
                || trimmed.eq_ignore_ascii_case("<!-- resolved -->")
            {
                resolved = true;
                continue;
            }
            if !line.starts_with("> [@") {
                if line.trim().is_empty() {
                    if let Some(r) = current.take() {
                        replies.push(r);
                    }
                }
                continue;
            }
            // Parse: > [@handle 2026-05-24T17:05:00Z] body...
            let rest = &line[3..]; // drop "> ["
            let Some(close_br) = rest.find(']') else { continue };
            let header = &rest[1..close_br]; // skip leading '@'
            let body_part = rest[close_br + 1..].trim_start();
            let mut it = header.splitn(2, ' ');
            let author = it.next().unwrap_or("").trim().to_string();
            let ts_str = it.next().unwrap_or("").trim();
            let created_at = parse_ts(ts_str).unwrap_or_else(Utc::now);
            match current.as_mut() {
                Some(r) if r.author == author && r.created_at == created_at => {
                    r.body.push('\n');
                    r.body.push_str(body_part);
                }
                _ => {
                    if let Some(r) = current.take() {
                        replies.push(r);
                    }
                    current = Some(Reply {
                        author,
                        body: body_part.to_string(),
                        created_at,
                    });
                }
            }
        }
        if let Some(r) = current.take() {
            replies.push(r);
        }
        if !replies.is_empty() || resolved {
            let entry = out.entry(tid).or_default();
            entry.replies.extend(replies);
            entry.resolved = entry.resolved || resolved;
        }
        cursor = body_end + end_marker.len();
    }
    out
}

fn parse_ts(s: &str) -> Option<DateTime<Utc>> {
    DateTime::parse_from_rfc3339(s).ok().map(|d| d.with_timezone(&Utc))
}
